### ISSUE TITLE
Swipe Action Doesn't work Properly in Right To Left Languages

### ISSUE THREAD

**Issue by Addallah** [X901/FXSwipeAction#1]
When Swiping to Close a Card for Example in Right To Left Languaes such as Arabic ,the card doesn't move in the right direction with the User finger, insted you will need to swipe in the other direction to close the Card.

https://github.com/X901/FXSwipeAction/assets/93667302/3e23004b-730a-473f-ac35-a002b2000d9e

A temporary solution is to Override the default EnvironmentValue for layouDirection and set it to `.leftToRight`

```swift
CardView()
  .fxSwipeActions(
	   leading: FXSwipeActionButton(
	   iconType: .system("trash.fill"),
           type: .leading,
           action: {
                // action()
           },
           tint: Color.pink
 ),
	 trailing: FXSwipeActionButton(
	 iconType: .system("star.fill"),
         type: .trailing,
	 action: {
	      // action()
	 },
          tint: Color.Primary
))
.environment(\.layoutDirection, .leftToRight)
```

**Comment by X901** [comment]
Fixed in version 1.1.0 
now the library suppourt both RTL and LTR languages
