### ISSUE TITLE
Receiving invalid response at pkg URL

### ISSUE THREAD

**Issue by marksili** [X901/FXSwipeAction#2]
I tried adding the package dependency using the https://github.com/X901/FXSwipeAction.git link, but I'm getting the following error:

 Received invalid response at https://github.com/X901/
FXSwipeAction.git. Please make sure it is a package collection URL.

**Comment by Addallah** [comment]
Are you using Swift Package Manager ?

**Comment by marksili** [comment]
Yes sir

**Comment by X901** [comment]
> I tried adding the package dependency using the https://github.com/X901/FXSwipeAction.git link, but I'm getting the following error:
> 
> Received invalid response at https://github.com/X901/ FXSwipeAction.git. Please make sure it is a package collection URL.

You shouldn't try adding a package collection !
Instead, paste the URL into the top right search bar after going to `File` -> `Add Package Dependency`, then select the package, select the Project you want to add the dependency to and tap Add package.

<img width="1036" alt="Screenshot 2024-01-19 at 6 27 36 PM" src="https://github.com/X901/FXSwipeAction/assets/16876982/0c0336da-de8a-4963-8168-b43bc4a65d57">

**Comment by marksili** [comment]
Got it, thank you very much.
